name: Social Media

docPath: docs/database
disableOutputSchema: true

er:
  format: mermaid

exclude:
  - "*.__EFMigrationsHistory"

format:
  adjust: true
  sort: true

lint:
  requireTableComment:
    enabled: true
  requireColumnComment:
    enabled: true
